export const NO_LENGTH_TECHNIQUES = [
  { id: 'manicure-tradicional-manos', name: 'Manicure tradicional (Manos)' },
  { id: 'manicure-tradicional-pies', name: 'Manicure tradicional (Pies)' },
  { id: 'gel-semipermanente-manos', name: 'Gel semipermanente (Manos)' },
  { id: 'gel-semipermanente-pies', name: 'Gel semipermanente (Pies)' },
  { id: 'rubber-gel', name: 'Rubber Gel' },
  { id: 'kapping-acrilico', name: 'Kapping de acrilico' },
  { id: 'kapping-polygel', name: 'Kapping de polygel' },
  { id: 'tecnica-hibrida', name: 'Tecnica Hibrida' },
  { id: 'mantenimiento-acrilico', name: 'Mantenimiento de Acrilico' },
  { id: 'mantenimiento-rubber-gel', name: 'Mantenimiento de Rubber gel' },
  { id: 'mantenimiento-builder-gel', name: 'Mantenimiento de Builder gel' },
  { id: 'mantenimiento-polygel', name: 'Mantenimiento de Polygel' },
]

export const WITH_LENGTH_TECHNIQUES = [
  { id: 'acrilico', name: 'Acrilico' },
  { id: 'builder-gel', name: 'Builder Gel' },
  { id: 'polygel', name: 'Polygel' },
  { id: 'esculpidas-acrilico', name: 'Esculpidas en acrilico' },
  { id: 'esculpidas-polygel', name: 'Esculpidas en polygel' },
]

const DECORATION_PLACEHOLDER_IMAGE =
  'https://images.unsplash.com/photo-1610992015732-2449b76344bc?auto=format&fit=crop&w=700&q=80'

export const DECORATION_OPTIONS = [
  { name: 'Espejo', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Aurora', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Azucar', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Carey', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Blooming', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Polka dots', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Marmol', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Ojo de gato', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Relieve', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: '3D', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Francesas (4)', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Nail art simple', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Nail art complicado', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Encapsulado', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Naturaleza muerta', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Dijes', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Baby boomer', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Diseno de piedras', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Diseno de piedras elaborado', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Diseno completo Ojo de gato', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Diseno completo de francesas', image: DECORATION_PLACEHOLDER_IMAGE },
  { name: 'Diseno completo de color entero', image: DECORATION_PLACEHOLDER_IMAGE },
]

export const CARE_OPTIONS = [
  {
    id: 'change-shape',
    kind: 'change-shape',
    name: 'Cambio de forma',
    description: 'Ajuste de forma de la una.',
  },
  {
    id: 'retiro-acrilico',
    kind: 'retiro',
    value: 'acrilico',
    name: 'Retiro Acrilico',
    description: 'Retiro de sistema acrilico.',
  },
  {
    id: 'retiro-gel',
    kind: 'retiro',
    value: 'gel',
    name: 'Retiro Gel semipermanente',
    description: 'Retiro de sistema en gel semipermanente.',
  },
  {
    id: 'reposicion-acrilico',
    kind: 'reposicion',
    value: 'acrilico',
    name: 'Reposicion Acrilico',
    description: 'Reposicion por una en sistema acrilico.',
  },
  {
    id: 'reposicion-polygel',
    kind: 'reposicion',
    value: 'polygel',
    name: 'Reposicion Polygel',
    description: 'Reposicion por una en sistema polygel.',
  },
]

export const PRICE_TABLES = {
  PRICES_NO_LENGTH: {
    'Manicure tradicional (Manos)': 20,
    'Manicure tradicional (Pies)': 30,
    'Gel semipermanente (Manos)': 35,
    'Gel semipermanente (Pies)': 60,
    'Rubber Gel': 50,
    'Kapping de acrilico': 40,
    'Kapping de polygel': 45,
    'Tecnica Hibrida': 60,
    'Mantenimiento de Acrilico': 45,
    'Mantenimiento de Rubber gel': 35,
    'Mantenimiento de Builder gel': 55,
    'Mantenimiento de Polygel': 55,
  },
  PRICES_WITH_LENGTH: {
    Acrilico: { 1: 60, 2: 60, 3: 70, 4: 80, 5: 90, 6: 100 },
    'Builder Gel': { 1: 70, 2: 70, 3: 70 },
    Polygel: { 1: 70, 2: 70, 3: 80, 4: 90, 5: 100, 6: 110 },
    'Esculpidas en acrilico': { 1: 70, 2: 70, 3: 80, 4: 90, 5: 100, 6: 110 },
    'Esculpidas en polygel': { 1: 80, 2: 80, 3: 90, 4: 100, 5: 110, 6: 120 },
  },
  DECORATION_PRICES: {
    Espejo: 3,
    Aurora: 3,
    Azucar: 3,
    Carey: 15,
    Blooming: 5,
    'Polka dots': 5,
    Marmol: 5,
    'Ojo de gato': 5,
    Relieve: 10,
    '3D': 10,
    'Francesas (4)': 10,
    'Nail art simple': 10,
    'Nail art complicado': 20,
    Encapsulado: 5,
    'Naturaleza muerta': 5,
    Dijes: 15,
    'Baby boomer': 10,
    'Diseno de piedras': 10,
    'Diseno de piedras elaborado': 20,
    'Diseno completo Ojo de gato': 20,
    'Diseno completo de francesas': 15,
    'Diseno completo de color entero': 10,
  },
  TONE_EXTRA_PRICE: 5,
  CHANGE_SHAPE_PRICE: 15,
  RETIRO_PRICES: {
    none: 0,
    acrilico: 20,
    gel: 10,
  },
  REPOSICION_PRICES: {
    none: 0,
    acrilico: 6,
    polygel: 7,
  },
  NON_COMBINABLE_DECORATIONS: {
    Espejo: [],
    Aurora: [],
    Azucar: [],
    Carey: [],
    Blooming: [],
    'Polka dots': [],
    Marmol: [],
    'Ojo de gato': [],
    Relieve: [],
    '3D': [],
    'Francesas (4)': [],
    'Nail art simple': [],
    'Nail art complicado': [],
    Encapsulado: [],
    'Naturaleza muerta': [],
    Dijes: [],
    'Baby boomer': [],
    'Diseno de piedras': [],
    'Diseno de piedras elaborado': [],
    'Diseno completo Ojo de gato': [],
    'Diseno completo de francesas': [],
    'Diseno completo de color entero': [],
  },
}
